dist: xenial
language: python
python:
    - '3.7'

branches:
    only:
        - config_for_prod

before_scripts:
    - pip3 install pipenv
    - pipenv install

env:
    - ENV="PRODUCTION"
    - SECRET_KEY="sdbdfbjdfDsvsfdbfdsEJZH03"
    - DJANGO_SETTINGS_MODULE="purbeurre_project.settings.production"

services:
    - postgresql

script:
    - ./manage.py test

